export const SECURITY_AWS = `
## Regras AWS — Security (Policy.IAM, Secret.Vault, Certificate.TLS)

**REGRA CRÍTICA — Policy.IAM na mesma stack da Lambda**: \`Policy.IAM\` com \`attachTo: 'XyzFn'\` DEVE estar na MESMA stack TypeScript que o construct \`Fn.Lambda(stack, 'XyzFn', ...)\`. Nunca coloque o \`Policy.IAM\` de uma Lambda em uma stack separada — o synth não consegue localizar a Lambda em outra stack e cria uma role desvinculada, sem efeito. Se uma Lambda precisa de permissões, adicione o \`Policy.IAM\` logo abaixo do \`Fn.Lambda\` correspondente, no mesmo arquivo.

Sempre que a lógica que você está gerando para uma Lambda depende de permissão em outro recurso (ex: handler faz \`GetItem\`/\`PutItem\` num DynamoDB, lê de um bucket S3, publica num SNS), GERE o \`Policy.IAM\` correspondente NA MESMA resposta — nunca deixe isso como algo para o usuário resolver depois. Colocar "adicione uma policy depois ou o deploy vai travar" em \`warnings\` em vez de simplesmente criar o \`Policy.IAM\` é o mesmo tipo de referência inválida da regra 5 do Custom.Resource: o recurso (Lambda) existe, mas sem a permissão a lógica que você acabou de escrever falha ou — no caso de um \`Custom.Resource\`/Lambda de seed — trava o \`aws cloudformation deploy\` esperando uma resposta que nunca chega. Prefira escopar \`resources\` no ARN real do recurso (ex: \`arn:aws:dynamodb:*:*:table/<NomeDaTabela>\`) em vez de \`['*']\` — já gere certo, não gere permissivo demais com um warning pra apertar depois.

**REGRA — referenciar o ARN de um Secret.Vault:** same-stack, use o getter tipado: \`const secret = new Secret.Vault(stack, 'JwtSecret', {}); ... environment: { SECRET_ARN: secret.secretArn }\` e \`resources: [secret.secretArn]\`. Cross-stack, use \`ref('JwtSecret', 'SecretArn')\` ou a string \`'JwtSecret.SecretArn'\` — o synth resolve para o ARN real (Ref local ou Fn::ImportValue). O ÚNICO getter de referência do Vault é \`.secretArn\` (e \`.arn\`, equivalente) — não existem \`.secretId\`, \`.value\` etc.

**REGRA TLS no cliente Redis (CRÍTICO):** o synth liga \`transitEncryptionEnabled\` por padrão (\`true\`) — o ElastiCache passa a EXIGIR TLS. Um cliente ioredis que conecta em texto puro (\`new Redis({ host, port })\`) fica pendurado no handshake e a Lambda dá TIMEOUT (não erro claro). SEMPRE conecte com TLS: \`new Redis({ host: process.env.CACHE_HOST, port: Number(process.env.CACHE_PORT), tls: {} })\`. (Só omita \`tls: {}\` se você tiver explicitamente setado \`transitEncryptionEnabled: false\` no construct.) Como \`AuthToken\` fica desabilitado por padrão, não é preciso \`password\`.

**REGRA Redis em VPC**: para Redis numa VPC, SEMPRE informe \`subnetIds\` (os IDs lógicos das subnets, ex: \`['PrivateSubnet1', 'PrivateSubnet2']\`) e \`securityGroupIds\` — NUNCA use \`subnetGroupName\` com um id de subnet cru (ElastiCache exige um SubnetGroup, não uma subnet; o synth cria o \`AWS::ElastiCache::SubnetGroup\` a partir de \`subnetIds\`). Nas env vars da Lambda que conecta ao cache, use os getters tipados same-stack (\`const cache = new Cache.Redis(...); ... REDIS_HOST: cache.endpoint, REDIS_PORT: cache.port\`) ou, cross-stack, \`ref('ProductsCache', 'Endpoint')\`/a string \`'ProductsCache.Endpoint'\`.
`;
